DB:
  - data/**/*.sql

CORE:
  - any: ['src/**/*', '!src/server/scripts/*']

Script:
  - src/server/scripts/**/*.cpp
  - src/server/scripts/**/*.h

Documentation:
  - ./*.md

Bash:
  - ./*.sh
  - apps/**/*.sh

Cmake:
  - ./*.cmake

Workflow:
  - .github/workflows/*
