DB:
  - src/**/*.sql

CORE:
  - src/**/*.cpp
  - src/**/*.h

Script:
  - src/server/scripts/*.cpp
  - src/server/scripts/*.h

Documentation:
  - ./*.md

Bash:
  - ./*.sh

Cmake:
  - ./*.cmake

Workflow:
  - .github/workflows/*
