DB:
  - data/**/*

CORE:
  - any: ['src/**/*', 'src/**/*', '!src/server/scripts/*']

Script:
  - src/server/scripts/**/*
  - src/server/scripts/**/*

Documentation:
  - ./*.md

Bash:
  - ./*.sh

Cmake:
  - ./*.cmake

Workflow:
  - .github/workflows/*
