- regExp: ".*\\.sql+$"
  labels: ["DB"]
- regExp: ".*\\.(cpp|h)+$|^(src\\server\\scripts\\.*\\.(cpp|h))$"
  labels: ["CORE"]
- regExp: ".*\\.md+$"
  labels: ["Documentation"]
- regExp: ".*\\.sh+$"
  labels: ["Bash"]
- regExp: ".*\\.cmake+$"
  labels: ["Cmake"]
- regExp: ".*\\.yml+$"
  labels: ["Workflow"]
