version: '3.2'

services:

  ac-database:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    networks:
      - ac-network
    ports:
      - ${DB_EXTERNAL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
    volumes:
      - type: volume
        source: ac-database
        target: /var/lib/mysql

  ac-worldserver:
    stdin_open: true
    tty: true
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: ./docker/worldserver/Dockerfile
    networks:
      - ac-network
    ports:
      - ${WORLD_EXTERNAL_PORT:-8085}:8085
      - ${SOAP_EXTERNAL_PORT:-7878}:7878
    volumes:
      - type: bind
        source: ./docker/worldserver/bin
        target: /azerothcore/env/dist/bin
      - type: bind
        source: ${WORLDSERVER_ETC:-./docker/worldserver/etc}
        target: /azerothcore/env/dist/etc
      - type: bind
        source: ${WORLDSERVER_LOGS:-./docker/worldserver/logs}
        target: /azerothcore/env/dist/logs
      - type: bind
        source: ${WORLDSERVER_DATA:-./docker/worldserver/data}
        target: /azerothcore/env/dist/data
    depends_on:
      - ac-database

  ac-authserver:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/authserver/Dockerfile
    networks:
      - ac-network
    ports:
      - ${AUTH_EXTERNAL_PORT:-3724}:3724
    volumes:
      - type: bind
        source: ./docker/authserver/bin
        target: /azerothcore/env/dist/bin
      - type: bind
        source: ${AUTHSERVER_ETC:-./docker/authserver/etc}
        target: /azerothcore/env/dist/etc
      - type: bind
        source: ${AUTHSERVER_LOGS:-./docker/authserver/logs}
        target: /azerothcore/env/dist/logs
    depends_on:
      - ac-database

volumes:
  ac-database:

networks:
  ac-network:
