version: '3.4'

services:

  ac-database:
    image: azerothcore/database
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    networks:
      - ac-network
    ports:
      - ${DB_EXTERNAL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
    volumes:
      - type: volume
        source: ac-database
        target: /var/lib/mysql

  ac-worldserver:
    stdin_open: true
    tty: true
    image: azerothcore2/server
    restart: unless-stopped
    privileged: true
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    networks:
      - ac-network
    ports:
      - ${WORLD_EXTERNAL_PORT:-8085}:8085
      - ${SOAP_EXTERNAL_PORT:-7878}:7878
    volumes:
      - type: bind
        source: ./docker/server/data
        target: /azeroth-server/data
    depends_on:
      - ac-database

  ac-authserver:
    image: azerothcore2/server
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    environment:
      START_AS_AUTHSERVER: "true"
    networks:
      - ac-network
    ports:
      - ${AUTH_EXTERNAL_PORT:-3724}:3724
    depends_on:
      - ac-database

volumes:
  ac-database:

networks:
  ac-network:
