name: Codestyle
on:
  pull_request:

jobs:
  triage:
    runs-on: ubuntu-latest
    name: C++
    if: github.repository == 'azerothcore/azerothcore-wotlk'
    steps:
      - uses: actions/checkout@v4
      - name: Check core codestyle
        run: source ./apps/ci/ci-codestyle.sh
