name: main
on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # the result of the matrix will be the combination of all attributes, so we get os*compiler builds
        agent: [self-hosted]
        compiler: [clang]
    runs-on: ${{ matrix.agent }}
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    env:
      COMPILER: ${{ matrix.compiler }}
    if: github.repository == 'renaissance-wow/renaissance-core' && !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: var/ccache
          key: ccache:${{ matrix.agent }}:${{ matrix.compiler }}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.agent }}:${{ matrix.compiler }}:${{ github.ref }}
            ccache:${{ matrix.agent }}:${{ matrix.compiler }}
      - name: Configure OS
        run: source ./acore.sh install-deps
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Create conf/config.sh
        run: source ./apps/ci/ci-conf-core.sh
      - name: Process pending sql
        run: bash bin/acore-db-pendings
      - name: Build
        run: source ./apps/ci/ci-compile.sh
      - name: Dry run authserver
        run: source ./apps/ci/ci-dry-run.sh authserver
      - name: Dry run worldserver
        run: source ./apps/ci/ci-dry-run.sh worldserver
      - name: Check startup errors
        run: source ./apps/ci/ci-error-check.sh
      - name: Run unit tests
        run: source ./apps/ci/ci-run-unit-tests.sh
