name: cpp-check
on:
  push:
    branches:
      - "master"
    paths:
      - src/server/scripts/**
      - "!README.md"
      - "!docs/**"
  pull_request:
    paths:
      - src/server/scripts/**
      - "!README.md"
      - "!docs/**"

jobs:
  cpp-check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    name: cpp check
    steps:
      - uses: actions/checkout@v2
      - name: cpp check
        run: |
          sudo apt update -y
          sudo apt install -y cppcheck
          cppcheck --force --inline-suppr src/server/scripts/
