name: PR Labeler
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v3
        with:
          token: ${{ github.token }}
          configuration-path: .github/labeler.yml
          sync-labels: true
