name: PR Labeler
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: ${{ github.token }}
          configuration-path: .github/labeler.yml
          sync-labels: true
