name: PR Labeler
on:
    - pull_request_target

jobs:
    triage:
        runs-on: ubuntu-22.04.1
        steps:
            - uses: actions/labeler@v3
              with:
                  repo-token: ${{ secrets.AC_GITHUB_TOKEN }}
                  configuration-path: .github/labeler.yml
                  sync-labels: true
