name: windows-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: ['labeled', 'opened', 'synchronize', 'reopened']

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      BOOST_ROOT: C:\local\boost_1_79_0
    if: github.repository == 'azerothcore/azerothcore-wotlk' && (github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'run-build') || github.event.label.name == 'run-build')
    steps:
      - uses: actions/checkout@v2
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh init
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build
      - name: Dry run authserver
        shell: bash
        run: |
          cd var/build/obj/bin/Release
          ./authserver -dry-run
      - name: Dry run worldserver
        shell: bash
        run: |
          cd var/build/obj/bin/Release
          ./worldserver -dry-run
      - name: Copy dll files
        shell: bash
        run: |
          cp "/c/tools/mysql/mysql-8.0.31-winx64/libmysql.dll" "build/bin/Release/"
          cp "/c/Program Files/OpenSSL-Win64/bin/libcrypto-1_1-x64.dll" "build/bin/Release/"
          cp "/c/Program Files/OpenSSL-Win64/bin/libssl-1_1-x64.dll" "build/bin/Release/"
      - uses: actions/upload-artifact@v2
        with:
          name: windows-2022-MSVC17-release
          path: build/bin/Release
